const skillsArray = 
[
    //consultancy
    'Technical Writing', 'Communication Skills', 'Teamwork', 'Project Management', 'Leadership', 'Problem-Solving', 
    'Critical Thinking', 'Time Management', 'Conflict Resolution', 'Decision Making', 'Adaptability', 
    'Interpersonal Skills', 'Creativity', 'Public Speaking', 'Presentation Skills', 'Networking', 'Negotiation', 
    'Emotional Intelligence', 'Self-Motivation', 'Work Ethic', 'Analytical Skills', 'Customer Service', 
    'Operations Management', 'Human Resources', 'Market Research', 'Business Strategy','Sales Skills','Risk Management', 
    'Compliance',
    'Legal Research', 
    'Intellectual Property', 
    'Contract Negotiation', 
    'Continuous Improvement', 
    'Kaizen', 
    'Agile Methodologies', 
    'Scrum', 
    'Kanban', 'Total Quality Management (TQM)',
    'Just-in-Time (JIT)',
    'Supply Chain Analytics',
    'ERP Systems',
    'SAP',
    'Oracle ERP',
    'Microsoft Dynamics',
    'Business Intelligence',
    'Data Warehousing',
    'Data Mining',
    'Data Governance',
    'Master Data Management',
    'ETL (Extract, Transform, Load)',
    'Informatica',
    'Talend',
    'Data Modeling',
    'Data Architecture',
    'Big Data (Advanced)',
    'Hadoop (Advanced)',
    'Spark (Advanced)',
    'Data Lake',
    'Data Lakehouse',
    'Cloud Data Platforms',
    'Snowflake',
    'BigQuery',
    'Redshift',
    'Athena',
    'DataOps',
    'MLOps',
    'AI Governance',
    'AI Ethics',
    'AI Fairness',
    'Explainable AI (XAI)',
    'Autonomous Systems',
    'Robotic Process Automation (RPA)',
    'Natural Language Processing (NLP)',
    'Computer Vision (Advanced)',
    'Speech Recognition',
    'Text-to-Speech',
    'Speech-to-Text',
    'Virtual Assistants',
    'Chatbots',
    'Conversational AI',
    'Recommendation Systems',
    'Consulting',
    'Management Consulting',
    'Financial Consulting',
    'IT Consulting',
    'Human Resources Consulting',
    'Marketing Consulting',
    'Operations Consulting',
    'Strategy Consulting',
    'Healthcare Consulting',
    'Environmental Consulting',
    'Legal Consulting',
    'Risk Management Consulting',
    'Change Management Consulting',
    'Junior Product Management',
    'Strategic Planning',
    'Business Analysis',
    'Market Research',
    'Project Management',
    'Risk Management',
    'Change Management',
    'Organizational Development',
    'Business Process Improvement',
    'Stakeholder Management',
    'Management Consulting',
    'Data Analysis',
    'Performance Measurement',
    'Process Mapping',
    'SWOT Analysis',
    'Competitive Analysis',
    'Benchmarking',
    'Cost-Benefit Analysis',
    'Feasibility Studies',
    'Client Relationship Management',
    'Business Strategy',
    'Business Transformation',
    'Operational Excellence',
    'Financial Advisory',
    'HR Consulting',
    'IT Consulting',
    'Lean Six Sigma',
    'Mergers & Acquisitions',
    'Strategic Sourcing',
    'Vendor Management',
    'Governance, Risk, and Compliance',
    'Customer Experience Management',
    'Digital Transformation',
    'Supply Chain Management',
    'Performance Improvement',
    'Service Design',
    'Policy Analysis',
    'Program Evaluation',
    'Knowledge Management',
    'Executive Coaching',
    'Organizational Change',
    'Business Model Innovation',
    'Crisis Management',
    'Restructuring',
    'Cost Reduction',
    'Business Case Development',
    'Environmental Consulting',
    'Sustainability Consulting',
    'Public Relations Consulting',
    'Event Management',
    'Mediation and Negotiation',
    'Risk Consulting', 'Compliance Consulting', 'Business Transformation', 
    'Change Management', 'Process Improvement', 'Digital Transformation', 
    'Business Analysis', 'Competitive Analysis', 'Benchmarking', 
    'Performance Management', 'Organizational Design', 'Talent Management', 
    'Learning and Development', 'Succession Planning', 'Due Diligence', 
    'Restructuring', 'Turnaround Management', 'Interim Management', 
    'Outsourcing', 'Offshoring', 'Shared Services', 'Business Process Reengineering', 
    'Agile Transformation',

    //finance
    'Financial Analysis', 'Accounting', 'Corporate Finance', 'Investment Banking', 'Economics', 'Financial Modeling',
    'Investment Management',
    'Financial Planning and Forecasting',
    'Asset Management',
    'Portfolio Management',
    'Financial Reporting',
    'Taxation',
    'Auditing',
    'Banking Operations',
    'Capital Markets',
    'Wealth Management',
    'Financial Compliance',
    'Financial Markets',
    'Derivatives Trading',
    'Mergers and Acquisitions (M&A)',
    'Venture Capital',
    'Private Equity',
    'Corporate Treasury',
    'Quantitative Finance',
    'Financial Econometrics',
    'Financial Software (e.g., Bloomberg, Reuters)',
    'Stock/Market Trading',
    'Valuation',
    'Mergers and Acquisitions',
    'Hedge Funds',
    'Derivatives',
    'Fixed Income',
    'Equities',
    'Trading',
    'Financial Planning',
    'Budgeting',
    'Forecasting',


    //tech
    'React', 'Node.js', 'JavaScript', 'Frontend Development', 'Bootstrap', 'HTML', 'CSS', 'Redux', 'TypeScript', 
    'GraphQL', 'Webpack', 'Babel', 'Vue.js', 'Angular', 'SASS', 'RESTful APIs', 'jQuery', 'ES6', 'Git', 
    'Responsive Design', 'D3.js', 'Next.js', 'Python', 'C++', 'C', 'Java', 'Dart', 'Flutter', 'Firebase', 
    'MongoDB', 'PostgreSQL', 'SQL', 'Pandas', 'NumPy', 'Scikit-learn', 'TensorFlow', 'Keras', 'PyTorch', 
    'R Programming', 'MATLAB', 'Julia', 'Scala', 'Machine Learning', 'Deep Learning', 'NLP', 'Computer Vision', 
    'Reinforcement Learning', 'Time Series Analysis', 'Feature Engineering', 'Data Preprocessing', 'Model Evaluation', 
    'Model Validation', 'Big Data', 'Apache Spark', 'Hadoop', 'AWS', 'Azure', 'Google Cloud', 'Distributed Computing', 
    'Algorithm Design', 'Neural Networks', 'Bayesian Methods', 'Ensemble Methods', 'Model Deployment', 'A/B Testing', 
    'Experiment Design', 'Statistical Modeling', 'Predictive Modeling', 'Supervised Learning', 'Unsupervised Learning', 
    'Semi-Supervised Learning', 'Active Learning', 'Transfer Learning', 'Model Interpretability', 'Ethics in AI', 
    'Research Methodology', 'Data Visualization','DevOps', 
    'CI/CD', 
    'Cloud Computing', 
    'Containerization', 
    'Docker', 
    'Kubernetes', 
    'Microservices', 
    'Serverless', 
    'Networking (IT)', 
    'Cybersecurity', 
    'Ethical Hacking', 
    'Penetration Testing', 
    'Incident Response', 
    'Digital Forensics', 
    'Information Security', 
    'Data Privacy', 
    'GDPR Compliance', 
    'CISSP', 
    'CEH', 
    'CompTIA Security+', 
    'Systems Administration', 
    'Linux', 
    'Windows Server', 
    'Unix', 
    'Virtualization', 
    'VMware', 
    'Hyper-V', 
    'OpenStack', 
    'Storage Management', 
    'SAN', 
    'NAS', 
    'Backup and Recovery', 
    'Database Administration', 
    'Oracle', 
    'MySQL', 
    'SQL Server', 
    'NoSQL Databases', 
    'Cassandra', 
    'MongoDB Administration', 
    'Redis', 
    'Couchbase', 
    'Elasticsearch','Data Analysis',
    'Data Science',
    'Machine Learning Algorithms',
    'Model Evaluation and Validation',
    'C++ Programming',
    'Java Programming',
    'Scala Programming',
    'Julia Programming',
    'Optimization Algorithms',
    'Dimensionality Reduction',
    'Graph Theory',
    'Software Development',
    'Cloud Computing (e.g., AWS, Azure, Google Cloud)',
    'Hadoop (Advanced)',
    'Spark (Advanced)',
    'TensorFlow.js',
    'PyBrain',
    'Mallet',
    'Deeplearning4j',
    'Torch',
    'Apache Mahout',
    'Amazon Machine Learning',
    'MXNet',
    'H2O.ai',
    'IBM Watson',
    'Microsoft Azure Machine Learning',
    'Google Cloud AI Platform',
    'AutoML',
    'Hugging Face Transformers',
    'OpenAI GPT',
    'Apache MXNet',
    'Microsoft Cognitive Toolkit (CNTK)',
    'Theano',
    'Google Cloud AI',
    'Amazon AI',
    'Microsoft Azure AI',
    'NLTK (Natural Language Toolkit)',
    'AllenNLP',
    'fastText',
    'BERT',
    'GloVe',
    'Word2Vec',
    'ELMo',
    'XLNet',
    'RoBERTa',
    'T5',
    'DALL-E',
    'CLIP',
    'PyCaret',
    'XGBoost',
    'LightGBM',
    'CatBoost',
    'Prophet',
    'CausalNex',
    'TensorFlow Probability',
    'Edward',
    'OpenAI Gym',
    'Stable Baselines',
    'PyBullet',
    'Express.js',
    'Responsive Web Design',
    'Web Accessibility',
    'Progressive Web Apps (PWAs)',
    'Mobile App Development (iOS/Android)',
    'React Native',
    'Swift',
    'Kotlin',
    'State Management',
    'Version Control (Git)',
    'Web Performance Optimization',
    'Agile Methodology',
    'Test-Driven Development (TDD)',
    'Continuous Integration/Continuous Deployment (CI/CD)',
    'Serverless Architecture',
    'Web Security',
    'OAuth',
    'JWT (JSON Web Tokens)',
    'WebSockets',
    'WebRTC',
    'Responsive Images',
    'SEO (Search Engine Optimization)',
    'Google Analytics',
    'JavaScript',
    'C#',
    'Django',
    'Flask',
    'Ruby on Rails',
    'Artificial Intelligence',
    'Spark',
    'Kafka',
    'Jenkins',
    'GitHub',
    'Blockchain',
    'Solidity',
    'Cryptography',
    'IoT',
    'AR/VR',
    'Mobile Development',
    'Android Development',
    'iOS Development',
    'Unity',
    'Unreal Engine',
    'SciPy',
    'Matplotlib',
    'Seaborn',
    'R',
    'Excel',
    'Tableau',
    'Power BI',
    'SAS',
    'SPSS',
    'JIRA',
    'Confluence',
    'Nuxt.js',
    'PHP',
    'Laravel',
    'Symfony',
    'CodeIgniter',
    'Zend Framework',
    'Perl',
    'Go',
    'Rust',
    'Elixir',
    'Clojure',
    'Haskell',
    'Erlang',
    'Shell Scripting',
    'Bash',
    'PowerShell',
    'Ansible',
    'Chef',
    'Puppet',
    'Terraform',
    'Vagrant',
    'Nagios',
    'Prometheus',
    'Grafana',
    'Splunk',
    'ELK Stack',
    'Logstash',
    'Kibana',
    'Zabbix',
    'Travis CI',
    'CircleCI',
    'Bamboo',
    'GitLab CI',
    'Buddy',
    'CodePipeline',
    'CloudFormation',
    'CloudWatch',
    'AppDynamics',
    'New Relic',
    'Dynatrace',
    'PagerDuty',
    'Sentry',
    'Honeybadger',
    'Raygun',
    'AppSignal',
    'Rollbar',
    'LogRocket',
    'Mixpanel',
    'Segment',
    'Amplitude',
    'Heap',
    'FullStory',
    'Hotjar',
    'Crazy Egg',
    'Optimizely',
    'VWO',
    'Adobe Analytics',
    'Matomo',
    'Fathom',
    'KYC',
    'AML',
    'GDPR',
    'CCPA',
    'HIPAA',
    'SOX',
    'PCI DSS',
    'ISO 27001',
    'NIST',
    'COBIT',
    'ITIL',
    'TOGAF',
    'OSCP',
    'CISM',
    'CISA',
    'CCSP',
    'CRISC',
    'CGEIT',
    'CFE',
    'CIPP',
    'CIPT',
    'CIPM',
    'PMI-ACP',
    'PMP',
    'PgMP',
    'PfMP',
    'PRINCE2',
    'MSP',
    'MoP',
    'MoR',
    'P3O',
    'Lean Six Sigma',
    'AgilePM',
    'ITSM',
    'ITOM',
    'ITBM',
    'ITAM',
    'EAM',
    'SAM',
    'CMDB',
    'HRIS',
    'HCM',
    'ERP',
    'CRM',
    'SCM',
    'PLM',
    'SRM',
    'BI',
    'ETL',
    'Data Lakes',
    'MDM',
    'DQM',
    'Data Quality',
    'Data Catalog',
    'Data Lineage',
    'Data Profiling',
    'Data Masking',
    'Data Obfuscation',
    'Data Anonymization',
    'Data Pseudonymization',
    'Data Encryption',
    'Data Tokenization',
    'Data Wrangling',
    'Data Blending',
    'Data Engineering',
    'AIOps',
    'DevSecOps',
    'FinOps',
    'ChatOps',
    'GitOps',
    'NoOps',
    'FaaS',
    'BaaS',
    'PaaS',
    'IaaS',
    'SaaS',
    'DaaS',
    'XaaS',
    'CI',
    'CD',
    'CT',
    'CDE',
    'IaC',
    'CaaS',
    'DBaaS',
    'STaaS',
    'MBaaS',
    'RPA',
    'Hyperautomation',
    'Process Mining',
    'Business Process Automation',
    'Workflow Automation',
    'Robotic Process Automation',
    'Intelligent Automation',
    'Automation Anywhere',
    'Blue Prism',
    'UiPath',
    'Kofax',
    'ABBYY',
    'Pegasystems',
    'Nintex',
    'Appian',
    'Bizagi',
    'BonitaSoft',
    'Camunda',
    'Pega',
    'ServiceNow',
    'Jitterbit',
    'MuleSoft',
    'SnapLogic',
    'Dell Boomi',
    'Tibco',
    'Workato',
    'Zapier',
    'Tray.io',
    'Integrately',
    'n8n',
    'Integromat',
    'Parabola',
    'PieSync',
    'QuickBase',
    'Airtable',
    'Notion',
    'Coda',
    'Smartsheet',
    'Asana',
    'Trello',
    'ClickUp',
    'Monday.com',
    'Wrike',
    'Basecamp',
    'Zoho Projects',
    'Jira',
    'Azure DevOps',
    'GitHub Projects',
    'GitLab Issues',
    'Clubhouse',
    'Linear',
    'Clickup',
    'Waterfall',
    'Hybrid',
    'Lean',
    'Scrumban',
    'XP',
    'DSDM',
    'FDD',
    'TDD',
    'BDD',
    'ATDD',
    'SecOps',
    'NetOps',
    'SysOps',
    'AppOps',
    'BizOps',
    'ValueOps',
    'AgileOps',
    'LeanOps',
    'XOps',
    'CMMI',
    'ISO 9001',
    'ISO 20000',
    'ISO 31000',
    'ISO 22301',
    'ISO 45001',
    'ISO 50001',
    'FISMA',
    'CIS',
    'CSA',
    'OWASP',
    'CWE',
    'CVSS',
    'CVEs',
    'MITRE ATT&CK',
    'Cyber Kill Chain',
    'NIST CSF',
    'SANS Top 20',
    'ISACA',
    'ISC2',
    'GIAC',
    'CompTIA',
    'Offensive Security',
    'Palo Alto Networks',
    'Fortinet',
    'Check Point',
    'Cisco',
    'Juniper',
    'IBM Security',
    'McAfee',
    'Symantec',
    'Trend Micro',
    'Kaspersky',
    'Bitdefender',
    'Avast',
    'Sophos',
    'ESET',
    'CrowdStrike',
    'FireEye',
    'F5',
    'Barracuda',
    'Aruba',
    'Meraki',
    'Silver Peak',
    'Cato Networks',
    'Zscaler',
    'Forcepoint',
    'Proofpoint',
    'Tanium',
    'Rapid7',
    'Qualys',
    'Nessus',
    'Nmap',
    'Metasploit',
    'Burp Suite',
    'OWASP ZAP',
    'Nikto',
    'OpenVAS',
    'Retina',
    'Acunetix',
    'QualysGuard',
    'Tenable.io',
    'Rapid7 InsightVM',
    'UI/UX Design',
    'CorelDRAW',
    'Logo Design',
    'Branding',
    'User Research',
    'Valuation',
    'Mergers and Acquisitions',
    'Hedge Funds',
    'Derivatives',
    'Fixed Income',
    'Equities',
    'Trading',
    'Financial Planning',
    'Budgeting',
    'Forecasting',
    'Electrical Engineering',
    'Aerospace Engineering',
    'Manufacturing Engineering',
    'Automation',
    'CAM',
    'CAE',
    'Simulink',
    'FEA',
    'PLC Programming',
    'Testing', 'Failure Analysis', 'Regulatory Compliance',




    //videographyAndPhotography
    'Photography', 
    'Video Editing', 
    'Film Production',
    'Acting',
    'Anchoring',
    'Animation',
    'Audio Making/Editing',
    'Cinematography',
    'Video Making/Editing',
    'Videography',
    'Photo Editing',
    'Film Making',
    'Media','Adobe Lightroom', 'Capture One', 'Portrait Photography', 
    'Landscape Photography', 'Wildlife Photography', 'Event Photography', 
    'Commercial Photography', 'Product Photography', 'Fashion Photography', 
    'Wedding Photography', 'Black and White Photography', 'Street Photography', 
    'Aerial Photography', 'Drone Photography', 'Sports Photography', 
    'Astrophotography', 'Adobe Premiere Pro', 'Final Cut Pro', 
    'DaVinci Resolve', 'Avid Media Composer', 'After Effects', 
    'Visual Effects (VFX)', 'Color Grading', 'Storyboarding', 
    'Scriptwriting', 'Directing', 'Lighting', 'Sound Design', 
    'Audio Editing', 'Video Production', 'Live Streaming', 
    'Broadcasting', 'Documentary Filmmaking', 'Commercial Filmmaking', 
    'Music Videos', 'Corporate Videos', 'Event Videography', 
    'Drone Videography',

    //engineering
    'Quality Assurance', 
    'Quality Control', 
    'Lean Manufacturing', 
    'Six Sigma', 
    'Robotics', 
    'Arduino',
    'Raspberry Pi', 
    'Embedded Systems', 
    'FPGA', 
    'VHDL', 
    'Verilog', 
    'PCB Design', 
    'Eagle', 
    'Altium Designer', 
    'Circuit Design', 
    'Signal Processing', 
    'Control Systems', 
    'Digital Design', 
    'Analog Design', 
    'Power Electronics', 
    'RF Engineering', 
    'Telecommunications', 
    'Wireless Communication', 
    'Networking (Communications)', 
    '5G', 
    'LTE', 
    'IoT (Internet of Things)', 
    'Smart Home Technologies', 
    'Wearable Technologies', 
    'Automotive Engineering', 
    'Mechanical Engineering', 
    'Thermodynamics', 
    'Fluid Dynamics', 
    'Heat Transfer', 
    'Solid Mechanics', 
    'Mechanical Design', 
    'ANSYS', 
    'CFD', 
    'Finite Element Analysis (FEA)', 
    'Manufacturing Processes', 
    'CNC Machining', 
    'Injection Molding', 
    '3D Printing (Manufacturing)', 
    'Materials Science', 
    'Metallurgy', 
    'Composite Materials', 
    'Polymers', 
    'Ceramics', 
    'Glass', 
    'Nanotechnology', 
    'Biotechnology', 
    'Genetic Engineering', 
    'Microbiology', 
    'Biochemistry', 
    'Molecular Biology', 
    'Cell Biology', 
    'Immunology', 
    'Pharmacology', 
    'Toxicology', 
    'Clinical Research', 
    'Regulatory Affairs', 
    'GMP Compliance', 
    'Quality Management (Healthcare)', 
    'Healthcare Administration', 
    'Public Health', 
    'Epidemiology', 
    'Health Informatics', 
    'Electronic Health Records (EHR)', 
    'Medical Coding', 
    'Medical Billing', 
    'Healthcare Policy', 
    'Health Economics', 
    'Medical Writing', 
    'Biomedical Engineering', 
    'Medical Devices', 
    'Medical Imaging', 
    'Radiology', 
    'Nuclear Medicine', 
    'Surgical Technology', 
    'Physical Therapy', 
    'Occupational Therapy', 
    'Nursing', 
    'Patient Care', 
    'Emergency Medicine', 
    'Critical Care', 
    'Anesthesia', 
    'Surgery', 
    'Pediatrics', 
    'Geriatrics', 
    'Psychiatry', 
    'Psychology', 
    'Counseling', 
    'Social Work',
    'Aluminium Alloys',
    'Ship Components and Materials',
    'Stress-Strain Curves',
    'Strain Hardening',
    'Proof Stress',
    'Hull Girder Bending',
    'Ship Construction Techniques',
    'Alignment of Joining Edges',
    'Continuity at Openings',
    'Steel Types (HSLA, High Yield Steel)',
    'Surface Treatments (Mill Scale Removal, Zinc-Based Paint)',
    'Electrical Engineering',
  'Aerospace Engineering',
  'Manufacturing Engineering',
  'Automation',
  'CAM',
  'CAE',
  'Simulink',
  'FEA',
  'PLC Programming',
  'Mechatronics',
  'Fluid Mechanics',

    //design
    'User Experience (UX) Design', 
    'User Interface (UI) Design', 
    'Interaction Design', 
    'Graphic Design', 
    'Adobe Photoshop', 
    'Adobe Illustrator', 
    'Adobe InDesign', 
    'Sketch', 
    'Figma', 
    'InVision', 
    'Wireframing', 
    'Prototyping', 
    'Usability Testing', 
    'Human-Computer Interaction', 
    'A/B Testing (Design)', 
    'Information Architecture', 
    'Design Thinking', 
    'Service Design', 
    'Product Design', 
    'Industrial Design',
    'Interior Design', 
    'Architecture', 
    'Landscape Architecture',
    'Graphic Design',
    'Web Design',
    'Mobile App Design',
    'Motion Graphics',
    'Illustration',
    '3D Design',
    'Brand Design',
    'Print Design',
    'Exhibition Design',
    'CAD Modeling',
    'Fashion Design',
    'Wayfinding and Signage',
    'Typography',
    'Logo Design',
    'Merchandise Design',
    'Blender',
    '3D Modeling/Printing',
    'Material Design',
    'Adobe XD',
    'UI/UX Design',
    'CorelDRAW',
    'Logo Design',
    'Branding',
    'User Research','UX Research', 
    'UI Design', 'Visual Design', 'Design Systems', 'DesignOps', 
    'Customer Experience (CX)', 'Digital Product Management',

    //product
    'Product Management', 'Market Research', 'Brand Management', 'Marketing','3D Modeling', 
    'CAD', 
    'SolidWorks', 
    'AutoCAD', 
    '3D Printing', 
    'Prototyping (Hardware)',
    'Product Management',
    'Junior Product Management',
    'Product Development', 'Product Strategy', 'Roadmapping', 
    'Product Lifecycle Management', 'Product Marketing', 
    'Go-to-Market Strategy', 'Customer Development', 'MVP Development', 
    'Agile Product Management', 'Backlog Management', 'Sprint Planning', 
    'User Story Mapping', 'Product Analytics', 'Customer Journey Mapping', 
    'Feature Prioritization', 'Product Launch', 'Product Roadmap', 
    'Customer Feedback', 'Stakeholder Management', 'Cross-functional Team Leadership', 
    'OKRs', 'KPIs', 'Product Vision', 'Business Model Canvas', 
    'Lean Startup', 'Value Proposition', 'Pricing Strategy', 
    'Monetization', 'Churn Analysis', 'Customer Retention', 
    'Product Growth', 'User Engagement', 'SaaS Product Management', 
    'E-commerce Product Management', 'Mobile Product Management', 
    'Platform Product Management', 'API Product Management', 
    'Innovation Management',


    //others
    'Supply Chain Management','Entrepreneurship', 
    'Business Development', 
    'Search Engine Optimization (SEO)', 
    'Search Engine Marketing (SEM)', 
    'Social Media Marketing', 
    'Content Marketing', 
    'Email Marketing', 
    'Pay-Per-Click (PPC) Advertising', 
    'Google Ads', 
    'Facebook Ads', 
    'Web Analytics', 
    'Google Analytics', 
    'Conversion Rate Optimization (CRO)',
    'Education', 
    'Teaching', 
    'Curriculum Development', 
    'Instructional Design', 
    'Educational Technology', 
    'E-Learning', 
    'Distance Learning', 
    'Special Education', 
    'Early Childhood Education', 
    'K-12 Education', 
    'Higher Education', 
    'Academic Research', 
    'Grant Writing', 
    'Library Science', 
    'Information Literacy', 
    'Archival Science', 
    'Museum Studies', 
    'Art History', 
    'Fine Arts', 
    'Music Theory', 
    'Music Performance', 
    'Theater Arts', 
    'Drama', 
    'Dance', 
    'Choreography', 
    'Journalism', 
    'Broadcast Journalism', 
    'Photojournalism', 
    'Creative Writing', 
    'Copywriting', 
    'Editing', 
    'Proofreading', 
    'Publishing', 
    'Public Relations', 
    'Media Relations', 
    'Crisis Communications', 
    'Event Planning', 
    'Event Management', 
    'Hospitality Management', 
    'Travel Management', 
    'Tourism', 
    'Sports Management', 
    'Recreation Management', 
    'Leisure Studies', 
    'Outdoor Recreation', 
    'Environmental Science', 
    'Environmental Policy', 
    'Sustainability', 
    'Renewable Energy', 
    'Energy Management', 
    'Climate Science', 
    'Geology', 
    'Oceanography', 
    'Meteorology', 
    'Geographic Information Systems (GIS)', 
    'Remote Sensing', 
    'Urban Planning', 
    'Civil Engineering', 
    'Structural Engineering', 
    'Transportation Engineering', 
    'Highway Engineering', 
    'Railway Engineering', 
    'Airport Engineering', 
    'Construction Management', 
    'Surveying', 
    'Hydrology', 
    'Water Resources Engineering', 
    'Environmental Engineering', 
    'Geotechnical Engineering', 
    'Soil Mechanics', 
    'Pavement Engineering', 
    'Petroleum Engineering', 
    'Mining Engineering', 
    'Metallurgical Engineering', 
    'Chemical Engineering', 
    'Process Engineering', 
    'Safety Engineering', 
    'Industrial Engineering', 
    'Operations Research', 
    'Supply Chain Optimization', 
    'Logistics', 
    'Inventory Management', 
    'Warehouse Management', 
    'Production Planning', 
    'Lean Manufacturing (Advanced)',
    'Blogging',
    'Content Writing',
    'Culinary Arts',
    'Dietetics/Nutrition',
    'Hotel Management',
    'Law',
    'Music',
    'Subject Matter Expert (SME) (Physics, Chemistry, Maths, Biology, English)',
    'Translation',
    'Transcription',
    'Travel & Tourism',
    'Client Servicing',
    'Digital Marketing',
    'Human Resources (HR)',
    'Market/Business Research',
    'Recruitments',
    'Sales',
    'Management Consulting',
    'Financial Consulting',
    'IT Consulting',
    'Human Resources Consulting',
    'Marketing Consulting',
    'Operations Consulting',
    'Strategy Consulting',
    'Healthcare Consulting',
    'Environmental Consulting',
    'Legal Consulting',
    'Risk Management Consulting',
    'Change Management Consulting',
    'Financial Modeling',
    'Investment Management',
    'Financial Planning and Forecasting',
    'Asset Management',
    'Portfolio Management',
    'Financial Reporting',
    'Taxation',
    'Auditing',
    'Banking Operations',
    'Capital Markets',
    'Wealth Management',
    'Financial Compliance',
    'Financial Markets',
    'Derivatives Trading',
    'Mergers and Acquisitions (M&A)',
    'Venture Capital',
    'Private Equity',
    'Corporate Treasury',
    'Quantitative Finance',
    'Financial Econometrics',
    'Financial Software (e.g., Bloomberg, Reuters)',
    'Stock/Market Trading',
    'Acting',
    'Anchoring',
    'Animation',
    'Audio Making/Editing',
    'Cinematography',
    'Video Making/Editing',
    'Videography',
    'Photo Editing',
    'Film Making',
    'Media',
    'Sports',
    'Blogging',
    'Content Writing',
    'Culinary Arts',
    'Dietetics/Nutrition',
    'Hotel Management',
    'Law',
    'Music',
    'Subject Matter Expert (SME) (Physics, Chemistry, Maths, Biology, English)',
    'Translation',
    'Transcription',
    'Travel & Tourism',
    'Junior Product Management',
    'Client Servicing',
    'Digital Marketing',
    'Human Resources (HR)',
    'Market/Business Research',
    'Recruitments',
    'Sales',
    
    
];



function autocomplete(input) {
    const lowerInput = input.toLowerCase();
    return skillsArray.filter(skill => skill.toLowerCase().includes(lowerInput));
}

function getSurroundingSkills(skills, index, count) {
    const startIndex = Math.max(0, index - count);
    const endIndex = Math.min(skills.length, index + count + 1);
    const beforeSkills = skills.slice(startIndex, index).reverse();
    const afterSkills = skills.slice(index + 1, endIndex);
    return { beforeSkills, afterSkills };
}

function suggestSkills(inputSkill, excludeSkills) {
    const autocompleteResults = autocomplete(inputSkill);

    if (autocompleteResults.length === 0) {
        return [];
    }

    // Get indices of skills to include
    const includedSkills = skillsArray.filter(skill => !excludeSkills.includes(skill));
    const surroundingSkills = [];

    autocompleteResults.forEach(result => {
        const includedIndex = includedSkills.indexOf(result);
        if (includedIndex !== -1) {
            const { beforeSkills, afterSkills } = getSurroundingSkills(includedSkills, includedIndex, 2);
            surroundingSkills.push(...beforeSkills, result, ...afterSkills);
        }
    });

    // Remove duplicates while preserving order
    const uniqueSkills = [...new Set(surroundingSkills)];

    // Ensure at least 10 skills by adding more from the list if necessary
    const finalSkills = uniqueSkills.filter(skill => !excludeSkills.includes(skill));

    if (finalSkills.length < 10) {
        const additionalSkills = includedSkills.filter(skill => !finalSkills.includes(skill)).slice(0, 10 - finalSkills.length);
        finalSkills.push(...additionalSkills);
    }

    return finalSkills.slice(0, 10);
}

export {
  suggestSkills
}
